AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  CheckTransaction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-CheckTransaction
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: CheckTransaction
      CodeUri: src/CheckTransaction
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${EnvironmentTagName}/*
      Environment:
        Variables:
          SECRETS_NAMESPACE: !Sub /${EnvironmentTagName}/
          LOTUS_API: https://api.filscan.io:8700/rpc/v1
          VAULT_ADDRESS: f3q5trezq2brsqllznbr5x7xmvigzcwhtn6uosghs4mqlfoui6fygxtwehpxsoogimxmubdghuohqqhkpji2oq
          WEB3_PROVIDER: https://kovan.infura.io/v3/811bbb5a9fdb4b36b486bc3823cde725
          CONTRACT_ADDRESS: eC41bA46D6a477e0a004a8e30566f3e9e4a7684b
          MINTER_ADDRESS: E24904d381D075cf0c8912Bc3438f2cf0c720eDC
          THREAD_ID: bafky3kyq5eade3csb22i73povf3tum5utuyqc4hcazlt4272qc72ywq
          TEXTILE_PUB_KEY: bwafveealtrpdmiob4heale5lwe
      Events:
        WFilGETtransactioncheck:
          Type: HttpApi
          Properties:
            Path: /transaction/check
            Method: GET
            ApiId: !Ref WFil
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000
  WFil:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        openapi: '3.0'
        info:
          title: !Sub ${AWS::StackName}-HttpApi
          version: '1.0'
        paths:
          /transaction:
            get:
              responses: {}
          /wallet:
            post:
              responses: {}
          /wallet/balance:
            get:
              responses: {}
          /wallet/send:
            post:
              responses: {}
          /unwrap:
            get:
              responses: {}
          /wrap:
            post:
              responses: {}
          /transaction/check:
            get:
              responses: {}
      FailOnWarnings: true
      CorsConfiguration:
        AllowHeaders:
          - Authorization
          - Content-Type
        AllowMethods:
          - '*'
        ExposeHeaders:
          - Content-Length
          - Content-Type
        AllowOrigins:
          - '*'
  CreateWallet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-CreateWallet
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: CreateWallet
      CodeUri: src/CreateWallet
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
      Environment:
        Variables:
          HOST: https://webapi.pow.wfil.textile.io
      Events:
        WFilPOSTwallet:
          Type: HttpApi
          Properties:
            Path: /wallet
            Method: POST
            ApiId: !Ref WFil
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000
  GetWalletBalance:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-GetWalletBalance
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: GetWalletBalance
      CodeUri: src/GetWalletBalance
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
      Environment:
        Variables:
          HOST: https://webapi.pow.wfil.textile.io
      Events:
        WFilGETwalletbalance:
          Type: HttpApi
          Properties:
            Path: /wallet/balance
            Method: GET
            ApiId: !Ref WFil
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000
  SendFil:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-SendFil
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: SendFil
      CodeUri: src/SendFil
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
      Environment:
        Variables:
          HOST: https://webapi.pow.wfil.textile.io
      Events:
        WFilPOSTwalletsend:
          Type: HttpApi
          Properties:
            Path: /wallet/send
            Method: POST
            ApiId: !Ref WFil
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000
  CheckUnwrap:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-CheckUnwrap
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: CheckUnwrap
      CodeUri: src/CheckUnwrap
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${EnvironmentTagName}/*
      Events:
        WFilGETunwrap:
          Type: HttpApi
          Properties:
            Path: /unwrap
            Method: GET
            ApiId: !Ref WFil
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000
      Environment:
        Variables:
          SECRETS_NAMESPACE: !Sub /${EnvironmentTagName}/
          HOST: https://webapi.pow.wfil.textile.io
          WEB3_PROVIDER: https://kovan.infura.io/v3/811bbb5a9fdb4b36b486bc3823cde725
          CONTRACT_ADDRESS: eC41bA46D6a477e0a004a8e30566f3e9e4a7684b
          MINTER_ADDRESS: E24904d381D075cf0c8912Bc3438f2cf0c720eDC
  Wrap:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-Wrap
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: Wrap
      CodeUri: src/Wrap
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${EnvironmentTagName}/*
      Events:
        WFilPOSTwrap:
          Type: HttpApi
          Properties:
            Path: /wrap
            Method: POST
            ApiId: !Ref WFil
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000
      Environment:
        Variables:
          SECRETS_NAMESPACE: !Sub /${EnvironmentTagName}/
          THREAD_ID: bafky3kyq5eade3csb22i73povf3tum5utuyqc4hcazlt4272qc72ywq
          TEXTILE_PUB_KEY: bwafveealtrpdmiob4heale5lwe
  ListTransactions:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-ListTransactions
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: ListTransactions
      CodeUri: src/ListTransactions
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${EnvironmentTagName}/*
      Environment:
        Variables:
          SECRETS_NAMESPACE: !Sub /${EnvironmentTagName}/
          THREAD_ID: bafky3kyq5eade3csb22i73povf3tum5utuyqc4hcazlt4272qc72ywq
          TEXTILE_PUB_KEY: bwafveealtrpdmiob4heale5lwe
      Events:
        WFilGETtransaction:
          Type: HttpApi
          Properties:
            Path: /transaction
            Method: GET
            ApiId: !Ref WFil
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)